[package]
name = "aoc"
version = "0.1.0"
authors = ["denismaxim0v"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.0-rc1"
itertools = "0.10.1"